### ISSUE TITLE
search-symbol-32.png - Not found

### ISSUE THREAD

**Issue by RiemerBug** [odoe/gen4#2]
If you use the SEARCH, you get:
_esri/widgets/Search/images/search-symbol-32.png   404 - Not found_

**Comment by odoe** [comment]
This has been fixed in this repo and in the generator output as well.

I think I'll add a guide so users can learn how to fix this issue if it comes up with other widgets they may add during development.

Thanks!

**Comment by RiemerBug** [comment]
Thanks. I think a guide would be a great idea.
